name: build-frontend-turborepo

on:
  pull_request:
    branches:
      - dev
      - 'hotfix-*'
    types:
      - closed
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: read

jobs: 
  check-for-changes:
    name: Checking Changes
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/
    steps:
      - uses: actions/checkout@v4

      - name: Decide whether to run
        id: pathcheck
        shell: bash
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "push" && "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "Triggered by tag → always run"
            echo "run=true" >> $GITHUB_OUTPUT
          else
            BASE="${GITHUB_BASE_REF}"
            echo "Base branch: $BASE"

            CHANGED=$(git diff --name-only origin/$BASE...HEAD | grep -v '\.md$' || true)
            echo "Changed files (non-md):"
            echo "$CHANGED"

            if [[ "$BASE" == "dev" ]]; then
              DEV_CHANGED=$(echo "$CHANGED" | grep 'frontend/' || true)
              [[ -n "$DEV_CHANGED" ]] && echo "run=true" >> $GITHUB_OUTPUT || echo "run=false" >> $GITHUB_OUTPUT
            elif [[ "$BASE" == hotfix-* ]]; then
              [[ -n "$CHANGED" ]] && echo "run=true" >> $GITHUB_OUTPUT || echo "run=false" >> $GITHUB_OUTPUT
            else
              echo "run=false" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Stop if conditions not met
        if: steps.pathcheck.outputs.run != 'true'
        run: |
          echo "Conditions not met. Skipping workflow."
          exit 0
  AppNames:
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    needs: check-for-changes
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.get-frontend-apps.outputs.apps }}
    defaults:
      run:
        working-directory: ./frontend/
    steps:
      - name: Checkout dev
        if: github.ref == 'refs/heads/dev'
        uses: actions/checkout@v6
        with:
          ref: dev

      - name: Checkout tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}

      - name: Checkout hotfix branch
        if: startsWith(github.ref, 'refs/heads/hotfix-')
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Create Release for Tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true

      - name: Get Frontend App Names
        id: get-frontend-apps
        run: |
          cd ./apps
          APP_ARRAY=()
          for f in *; do
            [ -e "$f" ] || continue
            APP_ARRAY+=("\"$f\"")
          done
          IFS=,
          JSON="[${APP_ARRAY[*]}]"
          echo "apps=$JSON" >> $GITHUB_OUTPUT
          echo $JSON

  AppToS3:
    needs: AppNames
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJSON(needs.AppNames.outputs.apps) }}
    defaults:
      run:
        working-directory: ./frontend/
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install deps
        run: |
          pnpm install

      - name: Build frontend
        run: |
          pnpm turbo build --filter=${{ matrix.app }}

      - name: Assume federated role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_FED_ROLE_ARN }}
          role-session-name: Federal

      - name: Zip built Apps
        run: |
          cd ./apps/${{ matrix.app }}/build
          cp ../bootstrapjs.sh .
          zip -r ${{ matrix.app }}.zip .

      - name: Deploy Apps (dev)
        if: github.ref == 'refs/heads/dev'
        run: |
          aws s3 cp "./apps/${{ matrix.app }}/${{ matrix.app }}.zip" s3://${{ secrets.BUCKET_NAME }}/frontend/dev/${{ matrix.app }}.zip

      - name: Deploy Apps (tags)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          aws s3 cp "./apps/${{ matrix.app }}/${{ matrix.app }}.zip" s3://${{ secrets.BUCKET_NAME }}/frontend/${GITHUB_REF#refs/tags/}/${{ matrix.app }}.zip

      - name: Deploy Apps (hotfix)
        if: startsWith(github.ref, 'refs/heads/hotfix-')
        run: |
          aws s3 cp "./apps/${{ matrix.app }}/${{ matrix.app }}.zip" s3://${{ secrets.BUCKET_NAME }}/frontend/${GITHUB_REF#refs/heads/}/${{ matrix.app }}.zip 